---
- name: config file
  template:
    src: wakatime.cfg.j2
    dest: "{{ dotfiles_root }}/wakatime.cfg"
- name: config link
  file:
    src: "{{ dotfiles_root }}/wakatime.cfg"
    dest: ~/.wakatime.cfg
    state: link
