'.zshrc.d/bd.zsh':
  type: file
  url: https://raw.githubusercontent.com/Tarrasch/zsh-bd/master/bd.zsh
  refreshPeriod: 168h

'.local/share/nvim/site/autoload/plug.vim':
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 168h
