#!/usr/bin/env zsh

for f in $HOME/.zshrc.d/*.zsh; do
  source $f
done

source "$HOME/.zprezto/init.zsh"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz compinit
    compinit
fi

source "$(brew --prefix kube-ps1)/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1
