#!/usr/bin/env zsh

for f in $HOME/.zshrc.d/*.zsh; do
  source $f
done

source "$HOME/.zprezto/init.zsh"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz compinit
    compinit
fi
