---
- name: global aliases
  git_config: scope=global name={{ item.name }} value={{ item.value }}
  with_items:

  - name: alias.b
    value: 'branch'
  - name: alias.ba
    value: 'branch -a'
  - name: alias.ci
    value: 'commit'
  - name: alias.co
    value: 'checkout'

  - name: alias.d
    value: 'diff'
  - name: alias.dc
    value: 'diff --cached'

  - name: alias.gr
    value: 'log --graph'
  - name: alias.go
    value: 'log --graph --pretty=oneline --abbrev-commit'
  - name: alias.lo
    value: 'log --pretty=nice'
  - name: alias.lc
    value: 'log ORIG_HEAD.. --stat --no-merges'
  - name: alias.lp
    value: 'log --patch-with-stat'

  - name: alias.mffo
    value: 'merge --ff-only'
  - name: alias.mnff
    value: 'merge --no-ff'
  - name: alias.mt
    value: 'mergetool'
