---
- name: ensure packages installed
  become: yes
  pacman: name={{ item }} state=present
  with_items:
  - zsh
  - git

- name: ensure default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_bin }}"
  when: zsh_set_default is defined and zsh_set_default
