---

- name: source
  git:
    repo: https://github.com/tarjoilija/zgen
    dest: "{{ zgen_dir }}"
    version: master
    update: no

- name: loader
  template:
    src: zgen.zsh
    dest: "{{ zsh_modules_dir }}/_zgen.zsh"
  notify: zgen-source

- name: loader alias
  copy:
    content: alias zgen-source="{{ zgen_source_cmd }}"
    dest: "{{ zsh_modules_dir }}/alias_zgen.zsh"
