---

- name: source
  git:
    repo: https://github.com/tarjoilija/zgen
    dest: "{{ zgen_dir }}"
    version: master
    update: no

- name: zgen.d
  file: path={{ zgen_modules_dir }} state=directory recurse=yes

- name: zgen.d placeholder
  copy: dest={{ zgen_modules_dir }}/_.zsh content=''

- name: loader
  template:
    src: zgen.zsh
    dest: "{{ zsh_modules_dir }}/_zgen.zsh"
  notify: zgen-source

- name: loader alias
  copy:
    content: alias zgen-source="{{ zgen_source_cmd }}"
    dest: "{{ zsh_modules_dir }}/alias_zgen.zsh"

- name: system modules
  copy:
    src: files/system.zsh
    dest: "{{ zgen_modules_dir }}"
  notify: zgen-source
