#!/bin/zsh

source {{ dotfiles_root | replace('~', '$HOME') }}/zshrc.before

export ZPLUG_HOME="{{ zplug_home }}"
source $ZPLUG_HOME/init.zsh

zplug "zplug/zplug"

# prezto
zplug "sorin-ionescu/prezto", use:"init.zsh", nice:-20
zplug "sorin-ionescu/prezto", use:"modules/environment"
zplug "sorin-ionescu/prezto", use:"modules/history"
zplug "sorin-ionescu/prezto", use:"modules/utility"
zplug "sorin-ionescu/prezto", use:"modules/editor"
zplug "sorin-ionescu/prezto", use:"modules/tmux"
zplug "sorin-ionescu/prezto", use:"modules/terminal"
zplug "sorin-ionescu/prezto", use:"modules/homebrew", if:"[[ $OSTYPE == *darwin* ]]"

# utils
zplug "willghatch/zsh-saneopt", nice:-20
zplug "supercrabtree/k", nice:10
zplug "sharat87/zsh-vim-mode"
zplug "zsh-users/zsh-history-substring-search", nice:9
zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "clvv/fasd", use:"fasd", as:plugin
zplug "junegunn/fzf-bin", from:gh-r, as:command, rename-to:fzf

# completions
zplug "docker/docker", use:"contrib/completion/zsh", depth:1
zplug "zsh-users/zsh-completions", nice:9

# theme
zplug "mafredri/zsh-async", nice:8
zplug "sindresorhus/pure", nice:9

# local
zplug "{{ zsh_modules_dir }}", use:"*.zsh", from:local

if ! zplug check; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

source {{ dotfiles_root | replace('~', '$HOME') }}/zshrc.after
