---

- name: directories clear
  file: path={{ dotfiles_root }} state=absent
  when: dotfiles_reset

- name: directories create
  file: path={{ item }} state=directory recurse=yes
  with_items:
  - "{{ dotfiles_root }}"
  - "{{ dotfiles_bin }}"
