# Shell configuration
export EDITOR=vim
export HISTIGNORE="ls:ll:cd:cd -:pwd:exit:date:* --help"

# Paths configuration
export DOTFILES_ROOT=$HOME/.dotfiles
export DOTFILES_ZSH_ROOT=$DOTFILES_ROOT/rc/zsh
export PATH=$PATH:$DOTFILES_ROOT/bin

# Sourcing bootstraps
source $DOTFILES_ZSH_ROOT/bootstrap.zsh
source $DOTFILES_ZSH_ROOT/alias.zsh

# Sourcing plugins
for file ($DOTFILES_ZSH_ROOT/plugins/*.zsh); do
  source $file
done
unset file

# clean up duplicate paths
export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')
